---
abstract: 'Lock-based limits on cooperative multi-processing'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-ConcurrencyLimit
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Fcntl: 0
  File::Path: 0
  File::Temp: 0
  IO::File: 0
version: 0.10
